### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/Smart-LoRa-Gateway#1]
Use this thread to upload images

**Comment by shawaj** [comment]
![The-Things-Conference-2020-1024-min](https://user-images.githubusercontent.com/3359418/75617006-fab68b80-5b50-11ea-8453-852b8ed896bd.jpg)
![The-Things-Conference-2020-1089-1-min](https://user-images.githubusercontent.com/3359418/75617007-fc804f00-5b50-11ea-91a5-a90f5f6520f7.jpg)
![The-Things-Conference-2020-1081-1-min](https://user-images.githubusercontent.com/3359418/75617008-fe4a1280-5b50-11ea-8478-843fad27f525.jpg)
![The-Things-Conference-2020-1080-1-min](https://user-images.githubusercontent.com/3359418/75617010-0013d600-5b51-11ea-9be2-ad7e3644cdf6.jpg)

**Comment by shawaj** [comment]
![The-Things-Conference-2020-1099-1-min](https://user-images.githubusercontent.com/3359418/75617046-c394aa00-5b51-11ea-8b2c-7b7429045747.jpeg)

**Comment by shawaj** [comment]
![c3bda40e0f2f605102b0842d8610adca_original](https://user-images.githubusercontent.com/3359418/75617062-fa6ac000-5b51-11ea-864a-21a467a2c813.png)

**Comment by ChristopherRush** [comment]
![nebra-smart-gateway-github](https://user-images.githubusercontent.com/1878314/75990644-1fae5400-5eed-11ea-8226-1e45b8c2f18c.png)

**Comment by shawaj** [comment]
RAK2247 pinout...
![RAK 2247pinout](https://user-images.githubusercontent.com/3359418/96388607-eab3f080-11a1-11eb-87f0-c362e975841c.png)

**Comment by ryanteck** [comment]
For this I'd like to upload images properly to the repo, being comments on an issue really frustrates me as it's not the right way to do it at all. I'll go through and start working on it soon and strip these away.
